name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Build Docker Image
        run: docker build -t ecomarket-servicio-productos-servicios:prod .

      - name: Save Docker Image to Tar File
        run: docker save ecomarket-servicio-productos-servicios:prod -o ecomarket-servicio-productos-servicios-prod.tar

      - name: Copy Docker Image to Production Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          port: ${{ secrets.PROD_SERVER_PORT }}
          source: "ecomarket-servicio-productos-servicios-prod.tar"
          target: "/tmp/ecomarket-servicio-productos-servicios-prod.tar"

      - name: Load Docker Image and Run Container on Production Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          port: ${{ secrets.PROD_SERVER_PORT }}
          script: |
            docker load -i /tmp/ecomarket-servicio-productos-servicios-prod.tar
            docker stop ecomarket-servicio-productos-servicios-prod || true
            docker rm ecomarket-servicio-productos-servicios-prod || true
            docker run -d --name ecomarket-servicio-productos-servicios-prod -p 8080:8080 ecomarket-servicio-productos-servicios:prod
